# Generated by Django 6.0 on 2025-12-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("recette", "Recette"),
                            ("depense", "Dépense"),
                            ("both", "Les deux"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#0B74FF", max_length=7)),
                ("icon", models.CharField(default="FolderOpen", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
    ]
