# Generated by Django 4.1.7 on 2025-12-11 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transactions", "0002_make_description_exporter_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="reports/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "format_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "XLSX")], max_length=10
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("yearly", "Annuel"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("transaction_count", models.IntegerField(default=0)),
                (
                    "total_recettes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_depenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("last_downloaded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Téléchargement de rapport",
                "verbose_name_plural": "Téléchargements de rapports",
                "db_table": "report_downloads",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_date_7edf95_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_type_840495_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_categor_bf503b_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reportdownload",
            name="downloaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_downloads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportdownload",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="downloads",
                to="transactions.report",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="last_downloaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downloaded_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
