# Generated by Django 6.0 on 2025-12-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_report_reportdownload_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
    ]
