# Generated by Django 6.0 on 2025-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_allow_null_file_in_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("daily", "Quotidien"),
                    ("weekly", "Hebdomadaire"),
                    ("monthly", "Mensuel"),
                    ("annual", "Annuel"),
                    ("yearly", "Annuel"),
                    ("custom", "Personnalisé"),
                ],
                max_length=20,
            ),
        ),
    ]
