# Generated by Django 6.0 on 2025-12-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_report_report_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportdownload",
            name="report",
        ),
        migrations.RemoveField(
            model_name="reportdownload",
            name="downloaded_by",
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.DeleteModel(
            name="ReportDownload",
        ),
    ]
