# Generated by Django 4.1.7 on 2025-12-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrateur"), ("user", "Utilisateur")],
                default="user",
                max_length=20,
            ),
        ),
    ]
